### ISSUE TITLE
SocketException. Cannot login to WhatsApp

### ISSUE THREAD

**Issue by kaptainzero** [mgp25/WhatsAPINet#16]
A socketexception occurs when reaching the following line:
    this.pollMessage(); // stream start

This is the exception thrown as logged by visual studio:
    Exception:Thrown: "An established connection was aborted by the software in your host machine" (System.Net.Sockets.SocketException)
    A System.Net.Sockets.SocketException was thrown: "An established connection was aborted by the software in your host machine"
    Time: 2015/04/10 7:19:08 AM
    Thread:<No Name>[14168]

![pollmessage](https://cloud.githubusercontent.com/assets/680105/7083556/eb41a9d4-df52-11e4-8e3e-bf8d1070cd74.gif)

**Comment by mgp25** [comment]
`An established connection was aborted by the software in your host machine`

Your computer its closing the connection

**Comment by sadiqhirani** [comment]
what is the solution for this situation i am also still facing the same problem.

**Comment by hpatel4u** [comment]
@kaptainzero according to me add sleep before and after connect and login method. I am not sure but try once with it.

**Comment by sadiqhirani** [comment]
buddy i tried but cant find any solution
here is the jit error log

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Net.Sockets.SocketException (0x80004005): An established connection was aborted by the software in your host machine
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.Socket.Send(Byte[] buffer)
   at WhatsAppApi.WhatsNetwork.Socket_send(Byte[] data) in c:\Chat-API-NET-master\WhatsAppApi\WhatsNetwork.cs:line 215
   at WhatsAppApi.WhatsNetwork.SendData(Byte[] data) in c:\Chat-API-NET-master\WhatsAppApi\WhatsNetwork.cs:line 113
   at WhatsAppApi.WhatsAppBase.SendData(Byte[] data) in c:\Chat-API-NET-master\WhatsAppApi\Base\WhatsAppBase.cs:line 133
   at WhatsAppApi.WhatsAppBase.SendNode(ProtocolTreeNode node) in c:\Chat-API-NET-master\WhatsAppApi\Base\WhatsAppBase.cs:line 143
   at WhatsAppApi.WhatsApp.SendMessageWithBody(FMessage message, Boolean hidden) in c:\Chat-API-NET-master\WhatsAppApi\WhatsApp.cs:line 848
   at WhatsAppApi.WhatsApp.SendMessage(FMessage message, Boolean hidden) in c:\Chat-API-NET-master\WhatsAppApi\WhatsApp.cs:line 627
   at WhatsAppApi.WhatsApp.SendMessage(String to, String txt) in c:\Chat-API-NET-master\WhatsAppApi\WhatsApp.cs:line 32
   at Testing_Windows_Client.Web2WhatsApp.SendMessage(String no, String message) in c:\Testing Windows Client\Testing Windows Client\Web2WhatsApp.cs:line 93
   at Testing_Windows_Client.Form1.button1_Click(Object sender, EventArgs e) in c:\Testing Windows Client\Testing Windows Client\Form1.cs:line 33
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34014 built by: FX45W81RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Testing Windows Client
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Testing%20Windows%20Client/Testing%20Windows%20Client/bin/Debug/Testing%20Windows%20Client.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34003 built by: FX45W81RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
WhatsAppApi
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Testing%20Windows%20Client/Testing%20Windows%20Client/bin/Debug/WhatsAppApi.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
